import { ProjectAnalysisResult, generateHtmlReport } from '@cognitive-complexity/core';
import * as fs from 'fs';
import * as path from 'path';
import * as vscode from 'vscode';
import { LanguageClient } from 'vscode-languageclient/node';
import { MethodComplexity } from '../types';

async function getFavicon(context: vscode.ExtensionContext): Promise<string> {
  let faviconBase64 = '';
  try {
    const iconUri = vscode.Uri.file(context.asAbsolutePath('resources/icon.png'));
    const iconBuffer = await vscode.workspace.fs.readFile(iconUri);
    faviconBase64 = `data:image/png;base64,${Buffer.from(iconBuffer).toString('base64')}`;
  } catch (e) {
    console.error('Failed to read report icon:', e);
  }
  return faviconBase64;
}

async function findPotentialFiles(token: vscode.CancellationToken): Promise<vscode.Uri[]> {
  const excludePattern = '{**/node_modules/**,**/dist/**,**/out/**,**/build/**,**/.*/**}';
  return vscode.workspace.findFiles(
    '**/*.{ts,tsx,js,jsx,cs,dart,c,h,cpp,cc,cxx,hpp,hh,hxx}',
    excludePattern,
    undefined,
    token,
  );
}

async function filterIgnoredFiles(
  client: LanguageClient,
  files: vscode.Uri[],
): Promise<vscode.Uri[]> {
  const filePaths = files.map((f) => f.fsPath);
  const filteredPaths = await client.sendRequest<string[]>('cognitive-complexity/filterIgnored', {
    filePaths,
  });

  const validPaths = new Set(filteredPaths.map((p) => p.toLowerCase()));
  return files.filter((f) => validPaths.has(f.fsPath.toLowerCase()));
}

async function resolveLanguageId(file: vscode.Uri, ext: string): Promise<string> {
  if (ext === '.h') {
    try {
      const doc = await vscode.workspace.openTextDocument(file);
      const id = doc.languageId.toLowerCase();
      if (id === 'c' || id === 'cpp') return id;
    } catch {
      // Fall through to default
    }
    return 'c';
  }

  if (ext === '.cs') return 'csharp';
  if (ext === '.js') return 'javascript';
  if (ext === '.jsx') return 'javascriptreact';
  if (ext === '.tsx') return 'typescriptreact';
  if (ext === '.dart') return 'dart';
  if (ext === '.c') return 'c';
  if (['.cpp', '.cc', '.cxx', '.hpp', '.hh', '.hxx'].includes(ext)) return 'cpp';
  return 'typescript';
}

async function analyzeSingleFile(client: LanguageClient, file: vscode.Uri): Promise<any | null> {
  try {
    const relativePath = vscode.workspace.asRelativePath(file).split(/[/\\]/).join('/');
    const ext = path.extname(file.fsPath).toLowerCase();
    const languageId = await resolveLanguageId(file, ext);

    const contentBuffer = await vscode.workspace.fs.readFile(file);
    const content = Buffer.from(contentBuffer).toString('utf8');

    if (languageId === 'csharp' && content.trimStart().startsWith('// <auto-generated')) {
      return null;
    }

    const complexities = await client.sendRequest<MethodComplexity[]>(
      'cognitive-complexity/analyzeFile',
      { uri: file.toString(), languageId, content },
    );

    return { file, relativePath, complexities, content, languageId };
  } catch (e) {
    console.error(`Failed to analyze ${file.fsPath}:`, e);
    return null;
  }
}

async function analyzeFileChunk(
  client: LanguageClient,
  chunk: vscode.Uri[],
): Promise<(any | null)[]> {
  return Promise.all(chunk.map((file) => analyzeSingleFile(client, file)));
}

function processSingleResult(res: any): any {
  if (!res || !res.complexities || res.complexities.length === 0) return null;

  const fileScore = res.complexities
    .filter((c: any) => c.isRoot)
    .reduce((acc: number, curr: any) => acc + curr.score, 0);

  return {
    path: res.relativePath,
    content: res.content,
    methods: (res.complexities as any[]).map(mapMethodComplexity),
    totalScore: fileScore,
    languageId: res.languageId,
  };
}

function processAnalysisResults(results: any[], reportData: ProjectAnalysisResult) {
  for (const res of results) {
    const fileResult = processSingleResult(res);
    if (fileResult) {
      reportData.files.push(fileResult);
      reportData.totalScore += fileResult.totalScore;
    }
  }
}

export async function generateProjectReport(
  client: LanguageClient,
  context: vscode.ExtensionContext,
) {
  const folder = vscode.workspace.workspaceFolders?.[0];
  if (!folder) {
    vscode.window.showErrorMessage('No workspace folder open');
    return;
  }

  try {
    await vscode.window.withProgress(
      {
        location: vscode.ProgressLocation.Notification,
        title: 'Generating Cognitive Complexity Report',
        cancellable: true,
      },
      async (progress, token) => {
        progress.report({ message: 'Finding files...' });
        const faviconBase64 = await getFavicon(context);

        let files = await findPotentialFiles(token);
        if (files.length === 0) {
          vscode.window.showInformationMessage(
            'No supported files found in workspace (checked ts, tsx, js, jsx, cs, dart, c, cpp).',
          );
          return;
        }

        if (token.isCancellationRequested) return;

        progress.report({ message: `Filtering ${files.length} files...` });
        files = await filterIgnoredFiles(client, files);

        if (files.length === 0) {
          vscode.window.showInformationMessage('No source files found (all were ignored by git).');
          return;
        }

        const reportData: ProjectAnalysisResult = {
          files: [],
          totalScore: 0,
          favicon: faviconBase64,
        };

        const analyzedFiles = await processFiles(files, client, progress, token, reportData);
        if (!analyzedFiles || token.isCancellationRequested) return;

        if (reportData.files.length === 0) {
          vscode.window.showInformationMessage('No complexity found in any of the analyzed files.');
          return;
        }

        progress.report({ message: 'Generating HTML report...' });
        const html = generateHtmlReport(reportData);
        const reportPath = path.join(folder.uri.fsPath, 'cognitive-complexity-report.html');

        await fs.promises.writeFile(reportPath, html, 'utf8');
        const selection = await vscode.window.showInformationMessage(
          `Report saved to ${path.basename(reportPath)}`,
          'Open in Browser',
        );

        if (selection === 'Open in Browser') {
          await vscode.env.openExternal(vscode.Uri.file(reportPath));
        }
      },
    );
  } catch (e) {
    vscode.window.showErrorMessage(`An error occurred: ${e}`);
  }
}

async function processFiles(
  files: vscode.Uri[],
  client: LanguageClient,
  progress: vscode.Progress<{ message?: string; increment?: number }>,
  token: vscode.CancellationToken,
  reportData: ProjectAnalysisResult,
): Promise<boolean> {
  const total = files.length;
  let analyzedCount = 0;
  const concurrency = 30;

  for (let i = 0; i < files.length; i += concurrency) {
    if (token.isCancellationRequested) return false;

    const chunk = files.slice(i, i + concurrency);
    const results = await analyzeFileChunk(client, chunk);
    processAnalysisResults(results, reportData);

    analyzedCount += chunk.length;
    progress.report({
      message: `Analyzed ${Math.min(analyzedCount, total)}/${total} files...`,
      increment: (chunk.length / total) * 100,
    });
  }
  return true;
}

function mapMethodComplexity(c: any): any {
  return {
    name: c.name,
    score: c.score,
    startLine: c.startLine,
    isCallback: !!c.isCallback,
    details: (c.details || []).map((d: any) => ({
      line: d.line,
      score: d.score,
      message: d.message,
    })),
  };
}
